# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
policies:
  - type: "commit"
    spec:
      dco: true
      gpg:
        required: true
      spellcheck:
        locale: "US"
...
