# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Actions"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions/*/action.yml"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  actions:
    name: "Actions"
    permissions:
      contents: "read"
    uses: "./.github/workflows/pdm-reusable.yml"
    with:
      prefix: "actions"
      checkout: ".github/actions/*/action.yml"
...
