# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Citation Renovate"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  cancel-in-progress: true
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}

jobs:
  citation-renovate:
    name: "Citation Renovate"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/renovate/dependencies-dev-citation'
    permissions:
      contents: "read"
    uses: "./.github/workflows/citation-reusable.yml"
...
