# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Ini"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.ini"
      - ".editorconfig"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ini:
    name: "Ini"
    permissions:
      contents: "read"
    uses: "./.github/workflows/ini-reusable.yml"
...
