# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "PR Labeler"

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - "opened"
      - "edited"
      - "synchronize"
      - "reopened"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  pr-labeler:
    timeout-minutes: 10
    name: "PR Labeler"
    permissions:
      contents: "read"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde" # v2.9.1
        # yamllint enable rule:line-length
        with:
          disable-sudo: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: "Checkout repository"
        # yamllint disable rule:line-length
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        # yamllint enable rule:line-length
        with:
          sparse-checkout: |
            .github/label*.yml
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - name: "Label PR"
        # yamllint disable rule:line-length
        uses: "actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9" # v5.0.0
        # yamllint enable rule:line-length
        with:
          configuration-path: ".github/label-path.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: "PR Labeler"
        # yamllint disable rule:line-length
        uses: "github/issue-labeler@6bea9ed491bb74fce38775b3d863e64a59dbd9eb" # v3.3
        # yamllint enable rule:line-length
        with:
          configuration-path: ".github/label-title.yml"
          enable-versioned-regex: 0
          sync-labels: 1
          include-title: 1
          include-body: 0
...
