# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Renovate"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**/renovate.json*"
      - "*.renovaterc.json*"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  renovate:
    name: "Renovate"
    permissions:
      contents: "read"
    uses: "./.github/workflows/pdm-reusable.yml"
    with:
      prefix: "renovate"
      checkout: |
        "**/renovate.json*"
        "*.renovaterc.json*"
...
