# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security Semgrep"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-semgrep:
    permissions:
      # Required to upload SARIF file to CodeQL.
      # See: https://github.com/github/codeql-action/issues/2117
      actions: "read"
      # Require writing security events to upload SARIF file to security tab
      security-events: "write"
      # Only need to read contents
      contents: "read"
    name: "Security Semgrep"
    uses: "./.github/workflows/security-semgrep-reusable.yml"
...
