# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Template Setup"

on:
  push:
    branches:
      - "main"

permissions: {} # yamllint disable-line rule:braces

jobs:
  skeleton:
    timeout-minutes: 30
    name: "Skeleton"
    permissions:
      contents: "write"
    if: >
      ! contains(github.repository, '*-template')
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6" # v2.8.1
        # yamllint enable rule:line-length
        with:
          disable-sudo: true
          egress-policy: "block"
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pdm-project.org:443
            pdm.fming.dev:443
            pypi.org:443
            raw.githubusercontent.com:443
      - name: "Check Description provided"
        # yamllint disable rule:indentation
        env:
          DESCRIPTION: "${{ github.event.repository.description }}"
        run: |
          if [ "${DESCRIPTION}" == "" ]; then
            echo "Repository description is missing"
            exit 1
          fi
        # yamllint enable rule:indentation
      - name: "Checkout repository" # zizmor: ignore[artipacked]
        # yamllint disable rule:line-length
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        # yamllint enable rule:line-length
      - name: "Setup template"
        uses: "./.github/actions/template-setup"
      - name: "Setup PDM"
        uses: "pdm-project/setup-pdm@b2472ca4258a9ea3aee813980a0100a2261a42fc"  # v4.2.0
      - name: "Create pdm.lock"
        run: >
          pdm lock -G:all -v
      - name: "Add pdm.lock license"
        # yamllint disable rule:line-length
        run: |
          echo "SPDX-FileCopyrightText: NONE" > pdm.lock.license
          echo "" >> pdm.lock.license
          echo "SPDX-License-Identifier: CC0-1.0" >> pdm.lock.license
        # yamllint enable rule:line-length
      - name: "Setup git credentials"
        uses: "./.github/actions/git-setup"
      - name: "Push changes"
        # __pypackages__ is ignored, but automatic PDM setup needs it for now
        run: |
          git add --all
          git add --force __pypackages__/README.md
          git commit -s -m "feat: setup repository [template]"
          git push
      - name: "Create gh-pages for documentation"
        run: |
          git switch --orphan gh-pages
          touch .nojekyll
          git add .nojekyll
          git commit -s -m "feat: setup gh-pages [template]"
          git push -u origin gh-pages
          git checkout main

  settings:
    timeout-minutes: 10
    name: "Settings"
    permissions:
      contents: "read"
      issues: "write"
    if: >
      ! contains(github.repository, 'pynudge')
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6" # v2.8.1
        # yamllint enable rule:line-length
        with:
          disable-sudo: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - name: "Checkout repository"
        # yamllint disable rule:line-length
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        # yamllint enable rule:line-length
        with:
          sparse-checkout: |
            template
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - name: "Remove default labels"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: >
          parallel -j0 --halt now,fail=1 'gh label delete {1} --yes'
          :::
          "bug"
          "documentation"
          "duplicate"
          "enhancement"
          "good first issue"
          "help wanted"
          "invalid"
          "question"
          "wontfix"
      - name: "Create necessary labels for .labeler.yml"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: >
          parallel -j0 --halt now,fail=1
          "gh label create {1} --force --description {2} --color {3}"
          :::
          announcement
          bot
          template
          actions
          deps
          config
          docs
          legal
          security
          tests
          src
          stale
          expired
          feat
          fix
          duplicate
          "help"
          invalid
          wontfix
          python
          question
          feat!
          fix!
          :::+
          "Announcements from maintainers"
          "Bot created changes"
          "Template updates"
          "GitHub Actions updates"
          "Dependencies updates"
          "Configuration files updates"
          "Documentation updates"
          "Legal documents updates"
          "Security updates"
          "Tests updates"
          "Source code updates"
          "Stale pull request"
          "Pull request is expired"
          "New feature or request"
          "Ongoing fix or bug report"
          "This issue or pull request already exists"
          "Maintainers need community help"
          "This issue or pull request is invalid"
          "This will not be worked on"
          "Python related changes"
          "Question about the project"
          "Breaking fix"
          "Breaking feature"
          :::+
          "#EA4335"
          "#9AA0A6"
          "#9AA0A6"
          "#2B3137"
          "#34A853"
          "#EA4335"
          "#34A853"
          "#EA4335"
          "#EA4335"
          "#EA4335"
          "#EA4335"
          "#9AA0A6"
          "#EA4335"
          "#34A853"
          "#EA4335"
          "#9AA0A6"
          "#EA4335"
          "#9AA0A6"
          "#9AA0A6"
          "#A4C330"
          "#34A853"
          "#EA4335"
          "#EA4335"
      - name: "Check dependency graph availability"
        id: "dependency_graph"
        env:
          GH_TOKEN: "${{ github.token }}"
          SBOM_ENDPOINT: "/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dependency-graph/sbom"
        # yamllint disable rule:line-length rule:indentation
        run: |
          if gh api "${SBOM_ENDPOINT}"; then
            echo "enabled=true" >> "${GITHUB_OUTPUT}"
          else
            echo "enabled=false" >> "${GITHUB_OUTPUT}"
          fi
        # yamllint enable rule:line-length rule:indentation
      - name: "Setup Python"
        # yamllint disable rule:line-length
        uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d" # v5.1.0
        # yamllint enable rule:line-length
        with:
          python-version: "3.x"
      - name: "Install cookiecutter"
        run: >
          pip install cookiecutter
      - name: "Create cookiecutter.json"
        id: "cookiecutter_file"
        # yamllint disable rule:line-length
        env:
          REPOSITORY: "${{ github.event.repository.name }}"
          REPOSITORY_OWNER: "${{ github.repository_owner }}"
          HAS_DEPENDENCY_GRAPH: "${{ steps.dependency_graph.outputs.enabled }}"
          HAS_DISCUSSIONS: "${{ github.event.repository.has_discussions }}"
          HAS_PAGES: "${{ github.event.repository.has_pages }}"
          WEB_COMMIT_SIGNOFF_REQUIRED: "${{ github.event.repository.web_commit_signoff_required }}"
        run: >
          ./template/create_cookiecutter_json.sh
          ./template/settings_issue/cookiecutter.json
          repository "\"${REPOSITORY}\""
          repository_owner "\"${REPOSITORY_OWNER}\""
          has_dependency_graph "${HAS_DEPENDENCY_GRAPH}"
          has_discussions "${HAS_DISCUSSIONS}"
          has_pages "${HAS_PAGES}"
          web_commit_signoff_required "${WEB_COMMIT_SIGNOFF_REQUIRED}"
        # yamllint disable rule:line-length
      - name: "Create issue from template"
        run: >
          cookiecutter --verbose --no-input template/settings_issue
          --output-dir settings_issue
      - name: "Create issue"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          REPOSITORY: "${{ github.event.repository.name }}"
        run: >
          gh issue create
          --title "Update repository settings"
          --label config,template,security
          --body-file
          "settings_issue/${REPOSITORY}/issue-body.md"

  initial-cache:
    needs: "skeleton"
    name: "Initial Cache"
    permissions:
      contents: "read"
    uses: "./.github/workflows/cache-reusable.yml"
...
