# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Template Update"

on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  citation:
    name: "Citation"
    permissions:
      contents: "write"
    uses: "./.github/workflows/template-update-reusable.yml"
...
