# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Template Update Reusable"

on:
  workflow_call:

permissions: {} # yamllint disable-line rule:braces

jobs:
  template-update-reusable:
    name: "Template Update"
    permissions:
      contents: "write"
    timeout-minutes: 10
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6" # v2.8.1
        # yamllint enable rule:line-length
        with:
          egress-policy: "audit"
      - name: "Placeholder operation"
        run: >
          echo "Placeholder operation, template update not implemented :("
...
