# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Tests Renovate"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  renovate-python-tests:
    name: "Tests Renovate"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      &&
      (
      github.ref == 'refs/heads/renovate/dependencies'
      || github.ref == 'refs/heads/renovate/dependencies-dev-test'
      )
    permissions:
      contents: "read"
    uses: "./.github/workflows/tests-reusable.yml"
...
