# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Workflows"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/*.yml"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

jobs:
  workflows:
    name: "Workflows"
    permissions:
      contents: "read"
    uses: "./.github/workflows/pdm-reusable.yml"
    with:
      prefix: "workflows"
      checkout: ".github/workflows/*.yml"
...
