# SPDX-FileCopyrightText: © 2024 nosludge <https://github.com/nosludge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "YAML Reusable"

on:
  workflow_call:

permissions: {} # yamllint disable-line rule:braces

jobs:
  yaml-reusable:
    name: "YAML Reusable"
    permissions:
      contents: "read"
    uses: "./.github/workflows/pdm-reusable.yml"
    with:
      prefix: "yaml"
      checkout: |
        **.yml
        **.yaml
...
